# Python для Анализа Данных

## Домашнее задание 4

### Вариант Light

In [224]:
import numpy as np

#### Задача 1

Подгрузите файл **train_vector.csv** с помощью функции **np.loadtxt**. Назовите подгруженный массив my_array. Убедитесь, что подгруженный массив имеет тип np.ndarray

In [225]:
my_array = np.loadtxt('train_vector.csv', delimiter=',')
print(f'тип файла:{type(my_array)}')

тип файла:<class 'numpy.ndarray'>


#### Задача 2

Возьмите функцию из предыдущих домашних заданий, которая считает сумму всех элементов массива. Примените ее к my_array.

In [226]:
def sum_(array):
    return np.sum(array)

sum_(my_array)

458.6

#### Задача 3

Напишите функцию, которая считает среднее значение всех элементов массива. Примените ее к подгруженному массиву my_array.

In [227]:
def aver(array):
    return np.mean(array)

aver(my_array)

3.0573333333333337

#### Задача 4

Напишите функцию, которая ищет минимальный элемент массива. Примените ее к подгруженному массиву my_array

In [228]:
def min_(array):
    return np.min(array)

min_(my_array)

2.0

#### Задача 5

Сравните производительность по времени с встроенными функциями: 

(В качестве переменной используйте подгруженный ранее массив my_array)
    
* np.sum
* np.mean
* np.min

P.S. используйте %%timeit

##### суммирование:

In [229]:
%%timeit
sum(my_array)

32.3 µs ± 3.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [230]:
%%timeit
my_array.sum()

2.37 µs ± 241 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [231]:
%%timeit
min_(my_array)

3.15 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


##### нахождение среднего:

In [232]:
%%timeit
my_array.mean()

4.84 µs ± 522 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [233]:
%%timeit
aver(my_array)

6 µs ± 509 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [234]:
%%timeit
sum(my_array) / len(my_array)

29.7 µs ± 646 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### нахождение минимального значения:

In [235]:
%%timeit
min(my_array)

16 µs ± 775 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [236]:
%%timeit
my_array.min()

2.32 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [237]:
%%timeit
min_(my_array)

2.86 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Задача 6
Преобразуйте исходный массив my_array в список (list). Назовите его my_list. Сравните производительность написанных вами функций в зависимости от типа данных (my_list и my_array). Сделайте вывод

In [238]:
my_list = list(my_array)
type(my_list)

list

##### суммирование:

In [239]:
%%timeit
sum_(my_array)

2.91 µs ± 317 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [240]:
%%timeit
sum_(my_list)

12.2 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


##### нахождение среднего:

In [241]:
%%timeit
aver(my_array)

5.34 µs ± 224 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [242]:
%%timeit
aver(my_list)

15.8 µs ± 990 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


##### нахождение минимального значения:

In [243]:
%%timeit
min_(my_array)

2.83 µs ± 195 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [244]:
%%timeit
min_(my_list)

13.4 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Задача 7

Сравните производительность написанных вами функций с встроенными функциями на массиве my_list. Сделайте вывод.

##### суммирование:

In [245]:
%%timeit
my_array.sum()

1.95 µs ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [246]:
%%timeit
sum(my_list)

16.7 µs ± 359 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


##### нахождение среднего:

In [247]:
%%timeit
my_array.mean()

4.37 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [248]:
%%timeit
sum(my_list) / len(my_list)

18.8 µs ± 448 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


##### нахождение минимального значения:

In [249]:
%%timeit
min(my_list)

4.43 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [250]:
%%timeit
min(my_list)

3.99 µs ± 98.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Задача 8

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напиишите функцию, которая считает сумму элементов массива по столбцам. 

In [251]:
my_2d_array = np.loadtxt('iris.csv', delimiter=',')
print(my_2d_array.shape)

(150, 4)


In [252]:
def np_sum_col(array):
    return np.sum(my_2d_array, axis=0)

In [253]:
np.sum(my_2d_array, axis =0)

array([876.5, 458.6, 563.7, 179.9])

#### Задача 9
* транспонируйте my_2d_array
* выполните матричное умножение my_2d_array на my_2d_array.T
* выполните матричное умножение my_2d_array.T на my_2d_array

In [254]:
print('\nразмер исходной:\n',
      my_2d_array.shape,
     '\n\nтранспонированная матрица:\n\n',
      my_2d_array.T,
      '\nразмер:\n',
      my_2d_array.T.shape,
      '\n\n2d_array на my_2d_array.T:\n\n',
      my_2d_array.dot(my_2d_array.T),
      '\nразмер:\n',
      my_2d_array.dot(my_2d_array.T).shape,
     '\n\n2d_array.T на my_2d_array:\n\n',
     my_2d_array.T.dot(my_2d_array),
     '\nразмер:\n',
     my_2d_array.T.dot(my_2d_array).shape)


размер исходной:
 (150, 4) 

транспонированная матрица:

 [[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2

#### Задача 10
Найдите в документации библиотеки numpy функцию, вычисляющую собственные числа матрицы.

Найдите собственные числа матриц (my_2d_array.T * my_2d_array) и (my_2d_array * my_2d_array.T) используя соответствующую функцию

In [255]:
np.linalg.eig(my_2d_array.dot(my_2d_array.T))

(array([ 9.20830507e+03+0.00000000e+00j,  3.15454317e+02+0.00000000e+00j,
         1.19780429e+01+0.00000000e+00j,  3.55257020e+00+0.00000000e+00j,
         8.20712565e-13+0.00000000e+00j, -4.33094080e-14+6.68123026e-13j,
        -4.33094080e-14-6.68123026e-13j, -6.42823339e-13+0.00000000e+00j,
        -2.07824941e-13+5.46853383e-13j, -2.07824941e-13-5.46853383e-13j,
        -4.87505161e-13+2.64151961e-13j, -4.87505161e-13-2.64151961e-13j,
         6.80722196e-14+5.32510787e-13j,  6.80722196e-14-5.32510787e-13j,
        -2.72814349e-13+4.60848097e-13j, -2.72814349e-13-4.60848097e-13j,
         5.17720768e-13+0.00000000e+00j,  2.78584495e-13+4.18362133e-13j,
         2.78584495e-13-4.18362133e-13j, -4.80969799e-13+0.00000000e+00j,
         2.89784951e-13+2.96687604e-13j,  2.89784951e-13-2.96687604e-13j,
         3.90383834e-13+1.24736332e-13j,  3.90383834e-13-1.24736332e-13j,
        -3.06006444e-14+3.48957061e-13j, -3.06006444e-14-3.48957061e-13j,
         3.31881219e-13+0.00000000e+00

In [256]:
np.linalg.eig(my_2d_array.T.dot(my_2d_array))

(array([9.20830507e+03, 3.15454317e+02, 1.19780429e+01, 3.55257020e+00]),
 array([[ 0.75110816,  0.2841749 ,  0.50215472,  0.32081425],
        [ 0.38008617,  0.5467445 , -0.67524332, -0.31725607],
        [ 0.51300886, -0.70866455, -0.05916621, -0.48074507],
        [ 0.16790754, -0.34367081, -0.53701625,  0.75187165]]))

### Вариант Pro

#### Задача 1

* Подгрузите массив **train_vector.csv** и назовите его my_array. 

* В документации библиотеки numpy найдите функцию, генерирующую случаные числа.

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array.

* Назовите его my_generated_array

In [257]:
my_array = np.loadtxt('train_vector.csv', delimiter = ',')
my_array.shape

(150,)

In [258]:
my_generated_array = np.random.randint(10, size=(150,))
my_generated_array.shape

(150,)

#### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array

* Транспонируйте my_generated_array

* Выполните матричное умножение my_array на транспонированный my_generated_array

* Выполните матричное умножение my_array.T на my_generated_array

In [259]:
my_array * my_generated_array

array([ 3.5, 24. , 25.6, 21.7,  3.6, 35.1, 20.4,  3.4, 14.5,  3.1,  7.4,
       10.2, 24. ,  6. , 16. , 22. , 27.3, 14. , 26.6, 11.4,  0. , 11.1,
        3.6,  9.9,  3.4, 15. ,  3.4, 10.5, 13.6,  3.2, 12.4, 23.8,  8.2,
       21. , 18.6,  9.6,  7. , 14.4, 24. , 10.2,  3.5, 16.1,  3.2, 21. ,
       15.2,  3. , 19. ,  6.4, 18.5,  6.6,  6.4,  0. , 15.5, 16.1,  2.8,
       14. , 29.7, 12. , 11.6, 21.6,  4. ,  6. , 19.8,  0. , 11.6,  3.1,
       27. , 24.3,  6.6, 22.5,  0. , 19.6,  2.5, 14. , 26.1,  3. ,  0. ,
       27. ,  8.7, 23.4,  0. , 19.2,  5.4,  0. , 21. , 10.2,  9.3,  6.9,
        0. ,  2.5,  0. ,  0. ,  7.8, 16.1,  5.4, 27. , 11.6,  8.7, 17.5,
        5.6,  3.3, 16.2, 27. ,  8.7, 12. , 24. , 15. ,  8.7,  2.5, 21.6,
       22.4,  2.7,  9. , 20. , 22.4, 22.4, 27. , 19. , 10.4, 13.2, 12.8,
       22.4, 22.4, 16.2, 23.1,  6.4, 25.2,  0. , 19.6,  3. , 22.4, 15.2,
       22.4,  5.6, 18.2, 27. ,  6.8, 12.4,  0. , 27.9,  0. , 15.5,  8.1,
        3.2, 29.7, 24. ,  0. , 27. , 13.6, 12. ])

In [260]:
my_generated_array.T

array([1, 8, 8, 7, 1, 9, 6, 1, 5, 1, 2, 3, 8, 2, 4, 5, 7, 4, 7, 3, 0, 3,
       1, 3, 1, 5, 1, 3, 4, 1, 4, 7, 2, 5, 6, 3, 2, 4, 8, 3, 1, 7, 1, 6,
       4, 1, 5, 2, 5, 2, 2, 0, 5, 7, 1, 5, 9, 5, 4, 8, 2, 2, 9, 0, 4, 1,
       9, 9, 3, 9, 0, 7, 1, 5, 9, 1, 0, 9, 3, 9, 0, 8, 2, 0, 7, 3, 3, 3,
       0, 1, 0, 0, 3, 7, 2, 9, 4, 3, 7, 2, 1, 6, 9, 3, 4, 8, 6, 3, 1, 6,
       7, 1, 3, 8, 8, 7, 9, 5, 4, 6, 4, 8, 8, 6, 7, 2, 9, 0, 7, 1, 8, 4,
       8, 2, 7, 9, 2, 4, 0, 9, 0, 5, 3, 1, 9, 8, 0, 9, 4, 4])

In [261]:
my_array.dot(my_generated_array)

1957.9

In [262]:
my_generated_array.dot(my_array)

1957.9

#### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием

In [263]:
my_array[((my_array > 3) & (my_array < 5))]

array([3.5, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 3.1, 3.7, 3.4, 4. , 4.4, 3.9,
       3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3.4, 3.5, 3.4, 3.2, 3.1,
       3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3.4, 3.5, 3.2, 3.5, 3.8, 3.8,
       3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 3.3, 3.1, 3.2, 3.4, 3.1, 3.3, 3.6,
       3.2, 3.2, 3.8, 3.2, 3.3, 3.2, 3.8, 3.4, 3.1, 3.1, 3.1, 3.1, 3.2,
       3.3, 3.4])

#### Задача 4

Даны два массива. 
* Найдите все общие элементы массивов (пересечение) при помощи встроенного метода.
* Напишите функцию, которая находит пересечение двух массивов (используйте структуру set)
* Сравните производительность по времени между np.intersect и вашей функцией. Для сравнения используйте %%timeit

In [264]:
a = np.array([17, 2, 3, 8, 5, 1990, 23, 36, 74])
b = np.array([37, 32, 12, 3, 25, 0, 17, 96, 54, 1990, 206])

In [265]:
%timeit np.intersect1d(a, b)

15.7 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [266]:
def common_elements(a, b):
    a_set, b_set = set(a), set(b)
    if (a_set & b_set):
        print(a_set & b_set)
    else:
        print('нет общих элементов')

In [267]:
%timeit common_elements(a,b)

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3, 1990}
{17, 3

In [268]:
%timeit list(set(a).intersection(b))

4.2 µs ± 83.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Задача 5

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных вещественных чисел от 17 до 23. Используйте встроенные методы библиотеки  np.random...

In [269]:
np.random.randint(17, 23, size=(2,3,4))

array([[[20, 17, 18, 22],
        [20, 20, 19, 20],
        [22, 21, 22, 21]],

       [[21, 20, 22, 18],
        [18, 20, 18, 19],
        [18, 22, 20, 18]]])

In [270]:
np.random.randint(17, 23, size=(2,3,4)).ndim

3

#### Задача 6

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:
    * "small", если значения меньше 19
    * "medium", если значения в промежутке [19, 21]
    * "large", если значения больше 21

In [271]:
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[17, 17, 20, 20],
        [17, 18, 17, 17],
        [18, 18, 21, 17]],

       [[17, 22, 20, 21],
        [20, 17, 19, 18],
        [20, 22, 21, 19]]])

In [272]:
np.where(my_array < 19, 'small', (np.where(my_array>21, 'large', 'medium')))

array([[['small', 'small', 'medium', 'medium'],
        ['small', 'small', 'small', 'small'],
        ['small', 'small', 'medium', 'small']],

       [['small', 'large', 'medium', 'medium'],
        ['medium', 'small', 'medium', 'small'],
        ['medium', 'large', 'medium', 'medium']]], dtype='<U6')

#### Задача 7

Преобразуйте массив из задачи 5 в "плоский" массив, т.е. вытяните существующий трехмерный массив в вектор при помощи встроенных методов библиотеки numpy

In [273]:
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[20, 17, 21, 21],
        [17, 20, 18, 18],
        [20, 21, 18, 17]],

       [[17, 19, 21, 17],
        [21, 19, 19, 22],
        [20, 18, 20, 19]]])

In [274]:
my_array.flatten()

array([20, 17, 21, 21, 17, 20, 18, 18, 20, 21, 18, 17, 17, 19, 21, 17, 21,
       19, 19, 22, 20, 18, 20, 19])

In [275]:
list(my_array.flat)

[20,
 17,
 21,
 21,
 17,
 20,
 18,
 18,
 20,
 21,
 18,
 17,
 17,
 19,
 21,
 17,
 21,
 19,
 19,
 22,
 20,
 18,
 20,
 19]

#### Задача 8: стандартизация данных

Напишите функцию, которая выполняет стандартизацию данных, т.е. преобразовывает их так, чтобы среднее значение стало равным нулю, а стандартное отклонение единице.

* загуглите что такое стандартизация и найдите формулу
* напишите функцию
* проверьте правильность выполнения функции на массиве из задачи 5


Записываю формулу стандартизации значений массива

$$ z = \frac{x_i - \mu}{\sigma}  $$

в функцию:

In [276]:
def stnd(array):
    result = (array - array.mean(axis=0) ) / (np.std(array))
    return result

In [277]:
# генерирую массив из задачи 5
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[17, 17, 18, 22],
        [18, 21, 21, 18],
        [22, 21, 17, 17]],

       [[17, 21, 21, 22],
        [19, 21, 21, 18],
        [17, 19, 19, 18]]])

In [278]:
# проверяю среднее
np.sum(stnd(my_array))/my_array.size == np.mean(stnd(my_array)) == 0

True

In [279]:
# проверяю стандартное отклонение 
np.std(stnd(my_array))

0.6030226891555273

стандартное отклонение не равно 1, скорее всего, это связано как то с 3 мерностью массива, поэтому попробую записать вручную:

In [280]:
def stnd_man(array): 
    # среднее
    mu = np.sum(array) / array.size
    # отклонение
    sigma = (np.sum((array - mu) ** 2)) / (array.size - 1)
    # стандратизирую
    res = (array - mu) / sigma
    return res

In [281]:
stnd_man(my_array)

array([[[-0.62727273, -0.62727273, -0.34848485,  0.76666667],
        [-0.34848485,  0.48787879,  0.48787879, -0.34848485],
        [ 0.76666667,  0.48787879, -0.62727273, -0.62727273]],

       [[-0.62727273,  0.48787879,  0.48787879,  0.76666667],
        [-0.06969697,  0.48787879,  0.48787879, -0.34848485],
        [-0.62727273, -0.06969697, -0.06969697, -0.34848485]]])

In [282]:
# но тут еще хуже
np.sum(stnd_man(my_array))

1.1102230246251565e-16

In [283]:
np.std(stnd_man(my_array))

0.516886561221819

**Задача 9**

* Напишите функцию, которая выполняет умножение двух матриц.
* Сравните производительность по времени своей функции со встроенным методом .dot

In [284]:
# генерирую 2 матрицы:
array1 = np.random.randint(1, 5, size=(4,2))
array2 = np.random.randint(1, 5, size=(2,4))
print(f'матрица 1:\n\n{array1}\n\nматрица 2:\n\n{array2}')

матрица 1:

[[3 3]
 [4 4]
 [3 1]
 [2 3]]

матрица 2:

[[3 1 3 2]
 [2 1 2 1]]


In [285]:
def mtrx_mlt(array1, array2):
    # завожу переменную под результирующую матрицу
    result = np.zeros((array1.shape[0], array1.shape[0]))
    # обхожу строки матрциы 1
    for i in range(array1.shape[0]):
        # обхожу столбцы матрицы 2
        for j in range(array2.shape[1]):
            # обхожу строки матрциы 1
            for el in range(array2.shape[0]):
                result[i][j] += array1[i][el] * array2[el][j]
    return result

In [286]:
mtrx_mlt(array1, array2)

array([[15.,  6., 15.,  9.],
       [20.,  8., 20., 12.],
       [11.,  4., 11.,  7.],
       [12.,  5., 12.,  7.]])

In [287]:
%timeit mtrx_mlt(array1, array2)

48 µs ± 3.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [288]:
array1.dot(array2)

array([[15,  6, 15,  9],
       [20,  8, 20, 12],
       [11,  4, 11,  7],
       [12,  5, 12,  7]])

In [289]:
%timeit array1.dot(array2)

892 ns ± 61.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
