# Python для Анализа Данных

## Домашнее задание 4

### Вариант Light

In [68]:
import numpy as np

#### Задача 1

Подгрузите файл **train_vector.csv** с помощью функции **np.loadtxt**. Назовите подгруженный массив my_array. Убедитесь, что подгруженный массив имеет тип np.ndarray

In [69]:
my_array = np.loadtxt('train_vector.csv', delimiter=',')
print(f'тип файла:{type(my_array)}')

тип файла:<class 'numpy.ndarray'>


#### Задача 2

Возьмите функцию из предыдущих домашних заданий, которая считает сумму всех элементов массива. Примените ее к my_array.

In [70]:
def sum_(array):
    sum_ = 0
    for i in array:
        sum_ += i
    return sum_

sum_(my_array)

458.60000000000014

#### Задача 3

Напишите функцию, которая считает среднее значение всех элементов массива. Примените ее к подгруженному массиву my_array.

In [71]:
def aver(array):
    sum_ = 0
    for i in array:
        sum_ += i
    return sum_ / len(array)

aver(my_array)

3.057333333333334

#### Задача 4

Напишите функцию, которая ищет минимальный элемент массива. Примените ее к подгруженному массиву my_array

In [72]:
def min_(array):
    min_ = 0
    for i in array:
        min_ = i if min_ is 0 or i < min_ else min_
    return min_

min_(my_array)

2.0

#### Задача 5

Сравните производительность по времени с встроенными функциями: 

(В качестве переменной используйте подгруженный ранее массив my_array)
    
* np.sum
* np.mean
* np.min

P.S. используйте %%timeit

##### суммирование:

In [73]:
%%timeit
sum(my_array)

43.6 µs ± 1.52 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [74]:
%%timeit
my_array.sum()

4.49 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
%%timeit
sum_(my_array)

49.5 µs ± 519 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### нахождение среднего:

In [76]:
%%timeit
my_array.mean()

9.8 µs ± 50.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
%%timeit
aver(my_array)

50.2 µs ± 430 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [78]:
%%timeit
sum(my_array) / len(my_array)

44.1 µs ± 404 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### нахождение минимального значения:

In [79]:
%%timeit
min(my_array)

23.9 µs ± 929 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [80]:
%%timeit
my_array.min()

5.07 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [81]:
%%timeit
min_(my_array)

33.1 µs ± 323 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### Задача 6
Преобразуйте исходный массив my_array в список (list). Назовите его my_list. Сравните производительность написанных вами функций в зависимости от типа данных (my_list и my_array). Сделайте вывод

In [82]:
my_list = list(my_array)
type(my_list)

list

##### суммирование:

In [83]:
%%timeit
sum_(my_array)

49.5 µs ± 925 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [84]:
%%timeit
sum_(my_list)

32.1 µs ± 214 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### нахождение среднего:

In [85]:
%%timeit
aver(my_array)

50.3 µs ± 345 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [86]:
%%timeit
aver(my_list)

33 µs ± 910 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### нахождение минимального значения:

In [87]:
%%timeit
min_(my_array)

33.3 µs ± 278 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [88]:
%%timeit
min_(my_list)

17.3 µs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Задача 7

Сравните производительность написанных вами функций с встроенными функциями на массиве my_list. Сделайте вывод.

##### суммирование:

In [89]:
%%timeit
my_array.sum()

4.41 µs ± 29.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [90]:
%%timeit
sum(my_list)

28 µs ± 283 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### нахождение среднего:

In [91]:
%%timeit
my_array.mean()

9.4 µs ± 890 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [92]:
%%timeit
sum(my_list) / len(my_list)

29.1 µs ± 182 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##### нахождение минимального значения:

In [93]:
%%timeit
min(my_list)

9.37 µs ± 66.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [94]:
%%timeit
min(my_list)

9.12 µs ± 485 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Задача 8

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напиишите функцию, которая считает сумму элементов массива по столбцам. 

In [95]:
my_2d_array = np.loadtxt('iris.csv', delimiter=',')
print(my_2d_array.shape)

(150, 4)


In [96]:
def np_sum_col(array):
    rslt = []
    for i in range(len(array[1])):
        sum_ = 0
        for j in array:
            sum_ += j
    rslt.append(sum_)
    return rslt

In [97]:
np_sum_col(my_2d_array)

[array([876.5, 458.6, 563.7, 179.9])]

In [98]:
np.sum(my_2d_array, axis =0)

array([876.5, 458.6, 563.7, 179.9])

#### Задача 9
* транспонируйте my_2d_array
* выполните матричное умножение my_2d_array на my_2d_array.T
* выполните матричное умножение my_2d_array.T на my_2d_array

In [99]:
print('\nразмер исходной:\n',
      my_2d_array.shape,
     '\n\nтранспонированная матрица:\n\n',
      my_2d_array.T,
      '\nразмер:\n',
      my_2d_array.T.shape,
      '\n\n2d_array на my_2d_array.T:\n\n',
      my_2d_array.dot(my_2d_array.T),
      '\nразмер:\n',
      my_2d_array.dot(my_2d_array.T).shape,
     '\n\n2d_array.T на my_2d_array:\n\n',
     my_2d_array.T.dot(my_2d_array),
     '\nразмер:\n',
     my_2d_array.T.dot(my_2d_array).shape)


размер исходной:
 (150, 4) 

транспонированная матрица:

 [[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2

#### Задача 10
Найдите в документации библиотеки numpy функцию, вычисляющую собственные числа матрицы.

Найдите собственные числа матриц (my_2d_array.T * my_2d_array) и (my_2d_array * my_2d_array.T) используя соответствующую функцию

In [100]:
np.linalg.eig(my_2d_array.dot(my_2d_array.T))

(array([ 9.20830507e+03+0.00000000e+00j,  3.15454317e+02+0.00000000e+00j,
         1.19780429e+01+0.00000000e+00j,  3.55257020e+00+0.00000000e+00j,
         8.20712565e-13+0.00000000e+00j, -4.33094080e-14+6.68123026e-13j,
        -4.33094080e-14-6.68123026e-13j, -6.42823339e-13+0.00000000e+00j,
        -2.07824941e-13+5.46853383e-13j, -2.07824941e-13-5.46853383e-13j,
        -4.87505161e-13+2.64151961e-13j, -4.87505161e-13-2.64151961e-13j,
         6.80722196e-14+5.32510787e-13j,  6.80722196e-14-5.32510787e-13j,
        -2.72814349e-13+4.60848097e-13j, -2.72814349e-13-4.60848097e-13j,
         5.17720768e-13+0.00000000e+00j,  2.78584495e-13+4.18362133e-13j,
         2.78584495e-13-4.18362133e-13j, -4.80969799e-13+0.00000000e+00j,
         2.89784951e-13+2.96687604e-13j,  2.89784951e-13-2.96687604e-13j,
         3.90383834e-13+1.24736332e-13j,  3.90383834e-13-1.24736332e-13j,
        -3.06006444e-14+3.48957061e-13j, -3.06006444e-14-3.48957061e-13j,
         3.31881219e-13+0.00000000e+00

In [101]:
np.linalg.eig(my_2d_array.T.dot(my_2d_array))

(array([9.20830507e+03, 3.15454317e+02, 1.19780429e+01, 3.55257020e+00]),
 array([[ 0.75110816,  0.2841749 ,  0.50215472,  0.32081425],
        [ 0.38008617,  0.5467445 , -0.67524332, -0.31725607],
        [ 0.51300886, -0.70866455, -0.05916621, -0.48074507],
        [ 0.16790754, -0.34367081, -0.53701625,  0.75187165]]))

### Вариант Pro

#### Задача 1

* Подгрузите массив **train_vector.csv** и назовите его my_array. 

* В документации библиотеки numpy найдите функцию, генерирующую случаные числа.

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array.

* Назовите его my_generated_array

In [102]:
my_array = np.loadtxt('train_vector.csv', delimiter = ',')
my_array.shape

(150,)

In [103]:
my_generated_array = np.random.randint(10, size=(150,))
my_generated_array.shape

(150,)

#### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array

* Транспонируйте my_generated_array

* Выполните матричное умножение my_array на транспонированный my_generated_array

* Выполните матричное умножение my_array.T на my_generated_array

In [104]:
my_array * my_generated_array

array([21. , 24. , 22.4,  9.3, 21.6, 19.5,  3.4,  3.4,  5.8, 21.7, 11.1,
        3.4, 27. , 12. ,  4. , 35.2, 23.4, 10.5, 30.4,  0. , 10.2, 14.8,
        3.6, 19.8,  3.4, 18. , 27.2, 28. ,  3.4, 22.4,  0. ,  3.4, 36.9,
       21. , 12.4,  6.4, 17.5, 14.4, 21. , 27.2, 21. , 16.1,  0. , 24.5,
       30.4,  6. , 34.2,  3.2,  0. ,  9.9,  3.2, 22.4, 12.4,  0. , 25.2,
        0. , 26.4, 16.8, 23.2,  8.1,  0. , 24. , 11. , 20.3, 20.3, 27.9,
       21. ,  2.7, 15.4,  0. , 19.2,  8.4,  7.5, 14. , 14.5, 18. , 25.2,
       15. , 23.2,  5.2, 19.2,  2.4, 10.8, 24.3, 18. , 23.8, 18.6,  0. ,
       21. , 17.5,  5.2,  0. , 23.4, 20.7, 10.8, 12. , 14.5, 20.3, 10. ,
        8.4,  0. , 21.6, 18. , 11.6, 27. , 24. ,  2.5, 11.6, 10. , 14.4,
        0. , 18.9,  9. , 15. ,  0. ,  6.4, 24. , 19. , 20.8,  2.2,  9.6,
       19.6, 22.4, 16.2, 29.7,  0. ,  8.4, 12. ,  0. , 27. ,  8.4, 30.4,
        2.8, 22.4,  0. ,  9. , 20.4,  3.1, 24. ,  6.2,  6.2, 24.8, 24.3,
        0. , 26.4, 15. ,  5. ,  6. ,  3.4, 12. ])

In [105]:
my_generated_array.T

array([6, 8, 7, 3, 6, 5, 1, 1, 2, 7, 3, 1, 9, 4, 1, 8, 6, 3, 8, 0, 3, 4,
       1, 6, 1, 6, 8, 8, 1, 7, 0, 1, 9, 5, 4, 2, 5, 4, 7, 8, 6, 7, 0, 7,
       8, 2, 9, 1, 0, 3, 1, 7, 4, 0, 9, 0, 8, 7, 8, 3, 0, 8, 5, 7, 7, 9,
       7, 1, 7, 0, 6, 3, 3, 5, 5, 6, 9, 5, 8, 2, 8, 1, 4, 9, 6, 7, 6, 0,
       7, 7, 2, 0, 9, 9, 4, 4, 5, 7, 4, 3, 0, 8, 6, 4, 9, 8, 1, 4, 4, 4,
       0, 7, 3, 6, 0, 2, 8, 5, 8, 1, 3, 7, 8, 6, 9, 0, 3, 4, 0, 9, 3, 8,
       1, 8, 0, 3, 6, 1, 8, 2, 2, 8, 9, 0, 8, 5, 2, 2, 1, 4])

In [106]:
my_array.dot(my_generated_array)

2127.5

In [107]:
my_generated_array.dot(my_array)

2127.5

#### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием

In [108]:
my_array[((my_array > 3) & (my_array < 5))]

array([3.5, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 3.1, 3.7, 3.4, 4. , 4.4, 3.9,
       3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3.4, 3.5, 3.4, 3.2, 3.1,
       3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3.4, 3.5, 3.2, 3.5, 3.8, 3.8,
       3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 3.3, 3.1, 3.2, 3.4, 3.1, 3.3, 3.6,
       3.2, 3.2, 3.8, 3.2, 3.3, 3.2, 3.8, 3.4, 3.1, 3.1, 3.1, 3.1, 3.2,
       3.3, 3.4])

#### Задача 4

Даны два массива. 
* Найдите все общие элементы массивов (пересечение) при помощи встроенного метода.
* Напишите функцию, которая находит пересечение двух массивов (используйте структуру set)
* Сравните производительность по времени между np.intersect и вашей функцией. Для сравнения используйте %%timeit

In [109]:
a = np.array([17, 2, 3, 8, 5, 1990, 23, 36, 74])
b = np.array([37, 32, 12, 3, 25, 0, 17, 96, 54, 1990, 206])

In [110]:
%timeit np.intersect1d(a, b)

33.4 µs ± 678 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [111]:
def common_elements(a, b):
    a_set, b_set = set(a), set(b)
    if (a_set & b_set):
        return a_set & b_set
    else:
        print('нет общих элементов')

In [112]:
%timeit common_elements(a,b)

9.12 µs ± 213 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [113]:
%timeit list(set(a).intersection(b))

7.92 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Задача 5

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных вещественных чисел от 17 до 23. Используйте встроенные методы библиотеки  np.random...

In [114]:
np.random.randint(17, 23, size=(2,3,4))

array([[[22, 22, 21, 20],
        [20, 20, 20, 22],
        [18, 21, 20, 19]],

       [[19, 21, 22, 22],
        [17, 17, 18, 18],
        [20, 21, 19, 18]]])

In [115]:
np.random.randint(17, 23, size=(2,3,4)).ndim

3

#### Задача 6

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:
    * "small", если значения меньше 19
    * "medium", если значения в промежутке [19, 21]
    * "large", если значения больше 21

In [116]:
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[20, 18, 20, 20],
        [22, 17, 18, 19],
        [18, 19, 21, 19]],

       [[18, 22, 22, 21],
        [18, 22, 20, 21],
        [22, 19, 18, 22]]])

In [117]:
np.where(my_array < 19, 'small', (np.where(my_array>21, 'large', 'medium')))

array([[['medium', 'small', 'medium', 'medium'],
        ['large', 'small', 'small', 'medium'],
        ['small', 'medium', 'medium', 'medium']],

       [['small', 'large', 'large', 'medium'],
        ['small', 'large', 'medium', 'medium'],
        ['large', 'medium', 'small', 'large']]], dtype='<U6')

#### Задача 7

Преобразуйте массив из задачи 5 в "плоский" массив, т.е. вытяните существующий трехмерный массив в вектор при помощи встроенных методов библиотеки numpy

In [118]:
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[21, 22, 18, 17],
        [17, 18, 18, 22],
        [22, 19, 21, 20]],

       [[19, 18, 20, 20],
        [22, 18, 18, 21],
        [18, 19, 20, 17]]])

In [119]:
my_array.flatten()

array([21, 22, 18, 17, 17, 18, 18, 22, 22, 19, 21, 20, 19, 18, 20, 20, 22,
       18, 18, 21, 18, 19, 20, 17])

In [120]:
list(my_array.flat)

[21,
 22,
 18,
 17,
 17,
 18,
 18,
 22,
 22,
 19,
 21,
 20,
 19,
 18,
 20,
 20,
 22,
 18,
 18,
 21,
 18,
 19,
 20,
 17]

#### Задача 8: стандартизация данных

Напишите функцию, которая выполняет стандартизацию данных, т.е. преобразовывает их так, чтобы среднее значение стало равным нулю, а стандартное отклонение единице.

* загуглите что такое стандартизация и найдите формулу
* напишите функцию
* проверьте правильность выполнения функции на массиве из задачи 5


Записываю формулу стандартизации значений массива

$$ z = \frac{x_i - \mu}{\sigma}  $$

в функцию:

In [121]:
def stnd(array):
    result = (array - array.mean(axis=0) ) / (np.std(array))
    return result

In [122]:
# генерирую массив из задачи 5
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[20, 19, 20, 21],
        [22, 17, 20, 21],
        [18, 22, 20, 19]],

       [[22, 17, 19, 21],
        [22, 18, 17, 17],
        [17, 17, 21, 20]]])

In [123]:
# проверяю среднее
np.sum(stnd(my_array))/my_array.size == np.mean(stnd(my_array)) == 0

True

In [124]:
# проверяю стандартное отклонение 
np.std(stnd(my_array))

0.6356587126210518

стандартное отклонение не равно 1, скорее всего, это связано как то с 3 мерностью массива, поэтому попробую записать вручную:

In [125]:
def stnd_man(array): 
    # среднее
    mu = np.sum(array) / array.size
    # отклонение
    sigma = (np.sum((array - mu) ** 2)) / (array.size - 1)
    # стандратизирую
    res = (array - mu) / sigma
    return res

In [126]:
stnd_man(my_array)

array([[[ 0.15980759, -0.13522181,  0.15980759,  0.45483699],
        [ 0.74986638, -0.7252806 ,  0.15980759,  0.45483699],
        [-0.4302512 ,  0.74986638,  0.15980759, -0.13522181]],

       [[ 0.74986638, -0.7252806 , -0.13522181,  0.45483699],
        [ 0.74986638, -0.4302512 , -0.7252806 , -0.7252806 ],
        [-0.7252806 , -0.7252806 ,  0.45483699,  0.15980759]]])

In [127]:
# но тут еще хуже
np.sum(stnd_man(my_array))

8.326672684688674e-15

In [128]:
np.std(stnd_man(my_array))

0.5317297288501227

**Задача 9**

* Напишите функцию, которая выполняет умножение двух матриц.
* Сравните производительность по времени своей функции со встроенным методом .dot

In [129]:
# генерирую 2 матрицы:
array1 = np.random.randint(1, 5, size=(4,2))
array2 = np.random.randint(1, 5, size=(2,4))
print(f'матрица 1:\n\n{array1}\n\nматрица 2:\n\n{array2}')

матрица 1:

[[1 3]
 [4 4]
 [3 4]
 [3 4]]

матрица 2:

[[2 3 1 1]
 [4 3 4 4]]


In [130]:
def mtrx_mlt(array1, array2):
    # завожу переменную под результирующую матрицу
    result = np.zeros((array1.shape[0], array1.shape[0]))
    # обхожу строки матрциы 1
    for i in range(array1.shape[0]):
        # обхожу столбцы матрицы 2
        for j in range(array2.shape[1]):
            # обхожу строки матрциы 1
            for el in range(array2.shape[0]):
                result[i][j] += array1[i][el] * array2[el][j]
    return result

In [131]:
mtrx_mlt(array1, array2)

array([[14., 12., 13., 13.],
       [24., 24., 20., 20.],
       [22., 21., 19., 19.],
       [22., 21., 19., 19.]])

In [132]:
%timeit mtrx_mlt(array1, array2)

86 µs ± 2.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [133]:
array1.dot(array2)

array([[14, 12, 13, 13],
       [24, 24, 20, 20],
       [22, 21, 19, 19],
       [22, 21, 19, 19]])

In [134]:
%timeit array1.dot(array2)

1.9 µs ± 5.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
