# Python для Анализа Данных

## Домашнее задание 4

### Вариант Light

In [58]:
import numpy as np

#### Задача 1

Подгрузите файл **train_vector.csv** с помощью функции **np.loadtxt**. Назовите подгруженный массив my_array. Убедитесь, что подгруженный массив имеет тип np.ndarray

In [59]:
my_array = np.loadtxt('train_vector.csv', delimiter=',')
print(f'тип файла:{type(my_array)}')

тип файла:<class 'numpy.ndarray'>


#### Задача 2

Возьмите функцию из предыдущих домашних заданий, которая считает сумму всех элементов массива. Примените ее к my_array.

In [60]:
def sum_(array):
    sum_ = 0
    for i in array:
        sum_ += i
    return sum_

sum_(my_array)

458.60000000000014

#### Задача 3

Напишите функцию, которая считает среднее значение всех элементов массива. Примените ее к подгруженному массиву my_array.

In [61]:
def aver(array):
    sum_ = 0
    for i in array:
        sum_ += i
    return sum_ / len(array)

aver(my_array)

3.057333333333334

#### Задача 4

Напишите функцию, которая ищет минимальный элемент массива. Примените ее к подгруженному массиву my_array

In [62]:
def min_(array):
    min_ = 0
    for i in array:
        min_ = i if min_ is 0 or i < min_ else min_
    return min_

min_(my_array)

2.0

#### Задача 5

Сравните производительность по времени с встроенными функциями: 

(В качестве переменной используйте подгруженный ранее массив my_array)
    
* np.sum
* np.mean
* np.min

P.S. используйте %%timeit

##### суммирование:

In [63]:
%%timeit
sum(my_array)

TypeError: 'int' object is not callable

In [ ]:
%%timeit
my_array.sum()

In [ ]:
%%timeit
min_(my_array)

##### нахождение среднего:

In [ ]:
%%timeit
my_array.mean()

In [ ]:
%%timeit
aver(my_array)

In [ ]:
%%timeit
sum(my_array) / len(my_array)

##### нахождение минимального значения:

In [ ]:
%%timeit
min(my_array)

In [ ]:
%%timeit
my_array.min()

In [ ]:
%%timeit
min_(my_array)

#### Задача 6
Преобразуйте исходный массив my_array в список (list). Назовите его my_list. Сравните производительность написанных вами функций в зависимости от типа данных (my_list и my_array). Сделайте вывод

In [ ]:
my_list = list(my_array)
type(my_list)

##### суммирование:

In [ ]:
%%timeit
sum_(my_array)

In [ ]:
%%timeit
sum_(my_list)

##### нахождение среднего:

In [ ]:
%%timeit
aver(my_array)

In [ ]:
%%timeit
aver(my_list)

##### нахождение минимального значения:

In [ ]:
%%timeit
min_(my_array)

In [ ]:
%%timeit
min_(my_list)

#### Задача 7

Сравните производительность написанных вами функций с встроенными функциями на массиве my_list. Сделайте вывод.

##### суммирование:

In [ ]:
%%timeit
my_array.sum()

In [ ]:
%%timeit
sum(my_list)

##### нахождение среднего:

In [ ]:
%%timeit
my_array.mean()

In [ ]:
%%timeit
sum(my_list) / len(my_list)

##### нахождение минимального значения:

In [64]:
%%timeit
min(my_list)

NameError: name 'my_list' is not defined

In [ ]:
%%timeit
min(my_list)

#### Задача 8

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напиишите функцию, которая считает сумму элементов массива по столбцам. 

In [ ]:
my_2d_array = np.loadtxt('iris.csv', delimiter=',')
print(my_2d_array.shape)

In [ ]:
def np_sum_col(array):
    rslt = []
    for i in range(len(array[1])):
        sum_ = 0
        for j in array:
            sum_ += j
    rslt.append(sum_)
    return rslt

In [ ]:
np_sum_col(my_2d_array)

In [ ]:
np.sum(my_2d_array, axis =0)

#### Задача 9
* транспонируйте my_2d_array
* выполните матричное умножение my_2d_array на my_2d_array.T
* выполните матричное умножение my_2d_array.T на my_2d_array

In [ ]:
print('\nразмер исходной:\n',
      my_2d_array.shape,
     '\n\nтранспонированная матрица:\n\n',
      my_2d_array.T,
      '\nразмер:\n',
      my_2d_array.T.shape,
      '\n\n2d_array на my_2d_array.T:\n\n',
      my_2d_array.dot(my_2d_array.T),
      '\nразмер:\n',
      my_2d_array.dot(my_2d_array.T).shape,
     '\n\n2d_array.T на my_2d_array:\n\n',
     my_2d_array.T.dot(my_2d_array),
     '\nразмер:\n',
     my_2d_array.T.dot(my_2d_array).shape)

#### Задача 10
Найдите в документации библиотеки numpy функцию, вычисляющую собственные числа матрицы.

Найдите собственные числа матриц (my_2d_array.T * my_2d_array) и (my_2d_array * my_2d_array.T) используя соответствующую функцию

In [ ]:
np.linalg.eig(my_2d_array.dot(my_2d_array.T))

In [ ]:
np.linalg.eig(my_2d_array.T.dot(my_2d_array))

### Вариант Pro

#### Задача 1

* Подгрузите массив **train_vector.csv** и назовите его my_array. 

* В документации библиотеки numpy найдите функцию, генерирующую случаные числа.

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array.

* Назовите его my_generated_array

In [ ]:
my_array = np.loadtxt('train_vector.csv', delimiter = ',')
my_array.shape

In [ ]:
my_generated_array = np.random.randint(10, size=(150,))
my_generated_array.shape

#### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array

* Транспонируйте my_generated_array

* Выполните матричное умножение my_array на транспонированный my_generated_array

* Выполните матричное умножение my_array.T на my_generated_array

In [ ]:
my_array * my_generated_array

In [ ]:
my_generated_array.T

In [ ]:
my_array.dot(my_generated_array)

In [ ]:
my_generated_array.dot(my_array)

#### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием

In [ ]:
my_array[((my_array > 3) & (my_array < 5))]

#### Задача 4

Даны два массива. 
* Найдите все общие элементы массивов (пересечение) при помощи встроенного метода.
* Напишите функцию, которая находит пересечение двух массивов (используйте структуру set)
* Сравните производительность по времени между np.intersect и вашей функцией. Для сравнения используйте %%timeit

In [ ]:
a = np.array([17, 2, 3, 8, 5, 1990, 23, 36, 74])
b = np.array([37, 32, 12, 3, 25, 0, 17, 96, 54, 1990, 206])

In [ ]:
%timeit np.intersect1d(a, b)

In [ ]:
def common_elements(a, b):
    a_set, b_set = set(a), set(b)
    if (a_set & b_set):
        return a_set & b_set
    else:
        print('нет общих элементов')

In [ ]:
%timeit common_elements(a,b)

In [ ]:
%timeit list(set(a).intersection(b))

#### Задача 5

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных вещественных чисел от 17 до 23. Используйте встроенные методы библиотеки  np.random...

In [ ]:
np.random.randint(17, 23, size=(2,3,4))

In [ ]:
np.random.randint(17, 23, size=(2,3,4)).ndim

#### Задача 6

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:
    * "small", если значения меньше 19
    * "medium", если значения в промежутке [19, 21]
    * "large", если значения больше 21

In [ ]:
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

In [ ]:
np.where(my_array < 19, 'small', (np.where(my_array>21, 'large', 'medium')))

#### Задача 7

Преобразуйте массив из задачи 5 в "плоский" массив, т.е. вытяните существующий трехмерный массив в вектор при помощи встроенных методов библиотеки numpy

In [ ]:
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

In [ ]:
my_array.flatten()

In [ ]:
list(my_array.flat)

#### Задача 8: стандартизация данных

Напишите функцию, которая выполняет стандартизацию данных, т.е. преобразовывает их так, чтобы среднее значение стало равным нулю, а стандартное отклонение единице.

* загуглите что такое стандартизация и найдите формулу
* напишите функцию
* проверьте правильность выполнения функции на массиве из задачи 5


Записываю формулу стандартизации значений массива

$$ z = \frac{x_i - \mu}{\sigma}  $$

в функцию:

In [65]:
def stnd(array):
    result = (array - array.mean(axis=0) ) / (np.std(array))
    return result

In [66]:
# генерирую массив из задачи 5
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[17, 21, 18, 21],
        [19, 19, 21, 21],
        [18, 21, 22, 20]],

       [[22, 18, 20, 18],
        [20, 18, 20, 21],
        [22, 18, 21, 19]]])

In [67]:
# проверяю среднее
np.sum(stnd(my_array))/my_array.size == np.mean(stnd(my_array)) == 0

False

In [68]:
# проверяю стандартное отклонение 
np.std(stnd(my_array))

0.8446972910537321

стандартное отклонение не равно 1, скорее всего, это связано как то с 3 мерностью массива, поэтому попробую записать вручную:

In [69]:
def stnd_man(array): 
    # среднее
    mu = np.sum(array) / array.size
    # отклонение
    sigma = (np.sum((array - mu) ** 2)) / (array.size - 1)
    # стандратизирую
    res = (array - mu) / sigma
    return res

In [70]:
stnd_man(my_array)

array([[[-1.18996139,  0.51505792, -0.76370656,  0.51505792],
        [-0.33745174, -0.33745174,  0.51505792,  0.51505792],
        [-0.76370656,  0.51505792,  0.94131274,  0.08880309]],

       [[ 0.94131274, -0.76370656,  0.08880309, -0.76370656],
        [ 0.08880309, -0.76370656,  0.08880309,  0.51505792],
        [ 0.94131274, -0.76370656,  0.51505792, -0.33745174]]])

In [71]:
# но тут еще хуже
np.sum(stnd_man(my_array))

-1.199040866595169e-14

In [72]:
np.std(stnd_man(my_array))

0.6391355165332376

**Задача 9**

* Напишите функцию, которая выполняет умножение двух матриц.
* Сравните производительность по времени своей функции со встроенным методом .dot

In [73]:
# генерирую 2 матрицы:
array1 = np.random.randint(1, 5, size=(4,2))
array2 = np.random.randint(1, 5, size=(2,4))
print(f'матрица 1:\n\n{array1}\n\nматрица 2:\n\n{array2}')

матрица 1:

[[2 1]
 [4 3]
 [3 2]
 [2 4]]

матрица 2:

[[2 3 4 3]
 [3 3 2 1]]


In [74]:
def mtrx_mlt(array1, array2):
    # завожу переменную под результирующую матрицу
    result = np.zeros((array1.shape[0], array1.shape[0]))
    # обхожу строки матрциы 1
    for i in range(array1.shape[0]):
        # обхожу столбцы матрицы 2
        for j in range(array2.shape[1]):
            # обхожу строки матрциы 1
            for el in range(array2.shape[0]):
                result[i][j] += array1[i][el] * array2[el][j]
    return result

In [75]:
mtrx_mlt(array1, array2)

array([[ 7.,  9., 10.,  7.],
       [17., 21., 22., 15.],
       [12., 15., 16., 11.],
       [16., 18., 16., 10.]])

In [76]:
%timeit mtrx_mlt(array1, array2)

86.3 µs ± 986 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [77]:
array1.dot(array2)

array([[ 7,  9, 10,  7],
       [17, 21, 22, 15],
       [12, 15, 16, 11],
       [16, 18, 16, 10]])

In [78]:
%timeit array1.dot(array2)

1.92 µs ± 3.01 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
