# Нейронные сети

## Домашнее задание 2: numpy и функции
**Полунина Полина**

## Light версия

In [1]:
import numpy as np

### Задача 1

Подгрузите файл **train_vector.csv** с помощью функции **np.loadtxt**. Назовите подгруженный массив my_array. Убедитесь, что подгруженный массив имеет тип np.ndarray

In [2]:
my_array = np.loadtxt('train_vector.csv', delimiter=',')
print(f'тип файла: {type(my_array)}')

тип файла: <class 'numpy.ndarray'>


### Задача 2

Напишите функцию, которая считает среднее значение всех элементов массива (без использования встроенных функций np.mean и т.д.)
* Примените ее к подгруженному массиву my_array
* Преобразуйте массив my_array в список, сохраните его в переменной my_list
* Примените функцию к списку my_list
* Сравните производительность по времени написанной вами функции в зависимости от типа данных (список и np.array), для этого используйте %%timeit

In [7]:
def sum_(array):
    sum_ = 0
    for i in my_list:
        sum_ += i
    return sum_

my_list = list(my_array)
print(f'сумма всех элементов заданного списка составляет: {sum_(my_array)}')
print(f'сумма всех элементов заданного списка составляет: {sum_(my_list)}')

сумма всех элементов заданного списка составляет: 458.60000000000014
сумма всех элементов заданного списка составляет: 458.60000000000014


In [8]:
%%timeit
sum_(my_array)

21.9 µs ± 2.05 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%%timeit
sum_(my_list)

21.2 µs ± 551 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Задача 3

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напиишите функцию, которая считает сумму элементов массива по столбцам. 

In [10]:
my_2d_array = np.loadtxt('iris.csv', delimiter=',')
print(my_2d_array.shape)

(150, 4)


In [12]:
def np_sum_col(array):
    rslt = []
    for i in range(len(array[1])):
        sum_ = 0
        for j in array:
            sum_ += j
    rslt.append(sum_)
    return rslt
np_sum_col(my_2d_array)

[array([876.5, 458.6, 563.7, 179.9])]

In [13]:
np.sum(my_2d_array, axis =0)

array([876.5, 458.6, 563.7, 179.9])

### Задача 4

* транспонируйте my_2d_array
* выполните матричное умножение my_2d_array на my_2d_array.T
* выполните матричное умножение my_2d_array.T на my_2d_array

In [14]:
print('\nразмер исходной:\n',
      my_2d_array.shape,
     '\n\nтранспонированная матрица:\n\n',
      my_2d_array.T,
      '\nразмер:\n',
      my_2d_array.T.shape,
      '\n\n2d_array на my_2d_array.T:\n\n',
      my_2d_array.dot(my_2d_array.T),
      '\nразмер:\n',
      my_2d_array.dot(my_2d_array.T).shape,
     '\n\n2d_array.T на my_2d_array:\n\n',
     my_2d_array.T.dot(my_2d_array),
     '\nразмер:\n',
     my_2d_array.T.dot(my_2d_array).shape)


размер исходной:
 (150, 4) 

транспонированная матрица:

 [[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2

### Задача 5

Напишите функцию, которая вычисляет значение следующей математической функции в зависимости от переменной х, где х - вектор

$F(x) = \frac{1}{25}AA^Tx + Bx + 5c$

* Создайте матрицы A и B размера 4 на 4, состоящие из случайных целых чисел в интервале от 1 до 10 (используйте соответствующую функцию модуля np.random)
* Создайте вектора х и с размера 4, состоящие из случайных целых чисел в интервале от 1 до 5

In [30]:
def func(x, A, B, c):
    f = 25**(-1)*A.dot(A.T)*x + B*x + 5*c
    return f

A = np.random.randint(1, 11, (4,4))
B = np.random.randint(1, 11, (4,4))
x, c = np.random.randint(1,6,4), np.random.randint(1,6,4)

func(x, A, B, c)

array([[ 79.2 ,  34.2 ,  29.16,  59.76],
       [ 63.  ,  23.  ,  34.  ,  57.04],
       [100.8 ,  29.  ,  34.08,  59.44],
       [ 97.2 ,  28.52,  34.36,  72.08]])

## Pro версия

### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* В документации библиотеки numpy найдите функцию, генерирующую случаные числа.

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array.

* Назовите его my_generated_array

In [35]:
my_array = np.loadtxt('iris.csv', delimiter=',')
print(my_array.shape)
my_generated_array = np.random.randint(1,100, my_array.shape)
print(my_generated_array.shape==my_array.shape)

(150, 4)
True


### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array

* Транспонируйте my_generated_array

* Выполните матричное умножение my_array на транспонированный my_generated_array

* Выполните матричное умножение my_array.T на my_generated_array

In [41]:
print(my_array * my_generated_array)

[[1.887e+02 1.575e+02 3.920e+01 7.800e+00]
 [3.920e+01 2.160e+02 1.232e+02 1.620e+01]
 [3.760e+02 2.080e+02 1.300e+00 1.740e+01]
 [3.772e+02 9.920e+01 2.850e+01 1.660e+01]
 [1.750e+02 5.760e+01 4.060e+01 1.920e+01]
 [2.808e+02 9.750e+01 5.440e+01 1.200e+00]
 [2.438e+02 1.870e+02 5.740e+01 3.300e+00]
 [1.650e+02 1.122e+02 5.100e+01 7.000e+00]
 [2.288e+02 1.015e+02 3.220e+01 1.980e+01]
 [4.116e+02 2.728e+02 4.500e+01 2.100e+00]
 [4.266e+02 1.628e+02 1.500e+00 1.020e+01]
 [2.256e+02 3.366e+02 1.584e+02 1.260e+01]
 [3.456e+02 4.500e+01 1.260e+01 8.200e+00]
 [6.020e+01 6.000e+01 7.260e+01 7.000e+00]
 [3.480e+02 3.240e+02 7.080e+01 5.000e+00]
 [2.052e+02 3.256e+02 4.050e+01 3.880e+01]
 [4.644e+02 3.510e+01 6.240e+01 3.840e+01]
 [4.743e+02 2.170e+02 6.580e+01 6.600e+00]
 [9.690e+01 3.800e+00 8.840e+01 2.760e+01]
 [3.825e+02 1.330e+02 1.200e+02 2.490e+01]
 [2.376e+02 1.734e+02 3.400e+01 1.140e+01]
 [1.479e+02 2.516e+02 1.050e+01 3.840e+01]
 [1.058e+02 3.420e+02 2.300e+01 2.200e+00]
 [3.060e+02

In [42]:
my_generated_array.T

array([[37,  8, 80, 82, 35, 52, 53, 33, 52, 84, 79, 47, 72, 14, 60, 36,
        86, 93, 17, 75, 44, 29, 23, 60, 86, 65,  1, 14, 23, 84, 14, 85,
        45, 14, 19, 40, 26, 39, 71, 39,  7, 32, 55, 46, 66, 55, 61, 97,
        76, 94, 58,  3, 62, 92, 51, 25, 25, 88, 13, 85,  6,  4, 40, 20,
        20, 44, 65, 18, 26, 81, 87, 17, 54, 47, 44, 73, 62, 11, 60, 93,
        77, 30, 93, 80, 47,  2, 45, 49, 91,  9, 62, 92, 30, 30, 89, 20,
        55, 97, 46, 33, 33, 80, 39, 77, 98, 81, 56,  6, 96, 19, 15, 90,
         4, 31, 46, 89, 62, 56,  1, 26, 62, 98, 84, 79, 11, 44, 47, 89,
         8, 11, 16, 91, 94, 98,  6, 42, 12, 71, 57, 79, 72, 58, 68, 89,
         1, 56, 66, 54, 37, 81],
       [45, 72, 65, 32, 16, 25, 55, 33, 35, 88, 44, 99, 15, 20, 81, 74,
         9, 62,  1, 35, 51, 68, 95, 27, 91,  9, 72, 33, 73, 25,  7, 71,
        25, 31, 16, 38, 88, 21, 85, 33, 62, 27,  7, 34, 46, 73, 63, 68,
        89, 82, 84, 23, 54,  7, 14, 23, 19, 19, 88, 69, 13, 34, 27,  4,
        42, 38, 44, 39, 24, 83,

In [43]:
my_array.dot(my_generated_array.T)

array([[393.2, 432.2, 654.3, ..., 586.6, 525. , 527.4],
       [363.3, 394.6, 605.8, ..., 535.8, 473.1, 505.7],
       [362.1, 398.6, 602.7, ..., 539.4, 482.6, 487.4],
       ...,
       [599.1, 887.6, 894.2, ..., 762.2, 676.3, 939.1],
       [623.3, 955.9, 922.5, ..., 794.4, 720.9, 951.2],
       [566.3, 857.8, 828.7, ..., 719.4, 641. , 870.6]])

In [45]:
my_array.T.dot(my_generated_array)

array([[44511.4, 41266.1, 40470.2, 47170.7],
       [23276. , 21733.6, 21010.1, 25037.9],
       [28863.2, 26490.8, 26189. , 29633.9],
       [ 9243.7,  8476.4,  8445. ,  9350. ]])

### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием

In [46]:
my_array[((my_array > 3) & (my_array < 5))]

array([3.5, 4.9, 4.7, 3.2, 4.6, 3.1, 3.6, 3.9, 4.6, 3.4, 3.4, 4.4, 4.9,
       3.1, 3.7, 4.8, 3.4, 4.8, 4.3, 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4,
       3.7, 4.6, 3.6, 3.3, 4.8, 3.4, 3.4, 3.5, 3.4, 4.7, 3.2, 4.8, 3.1,
       3.4, 4.1, 4.2, 4.9, 3.1, 3.2, 3.5, 4.9, 3.6, 4.4, 3.4, 3.5, 4.5,
       4.4, 3.2, 3.5, 3.8, 4.8, 3.8, 4.6, 3.2, 3.7, 3.3, 3.2, 4.7, 3.2,
       4.5, 3.1, 4.9, 4. , 4.6, 4.5, 3.3, 4.7, 4.9, 3.3, 4.6, 3.9, 3.5,
       4.2, 4. , 4.7, 3.6, 3.1, 4.4, 4.5, 4.1, 4.5, 3.9, 3.2, 4.8, 4. ,
       4.9, 4.7, 4.3, 4.4, 4.8, 4.5, 3.5, 3.8, 3.7, 3.9, 4.5, 3.4, 4.5,
       3.1, 4.7, 4.4, 4.1, 4. , 4.4, 4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3,
       4.1, 3.3, 4.9, 4.5, 3.6, 3.2, 3.2, 3.8, 3.2, 4.9, 4.9, 3.3, 3.2,
       4.8, 4.9, 3.8, 3.4, 3.1, 4.8, 3.1, 3.1, 3.1, 3.2, 3.3, 3.4])

### Задача 4

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных вещественных чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random...

In [50]:
my_array = np.random.randint(17, 23, size=(2,3,4))
my_array

array([[[20, 21, 17, 17],
        [18, 22, 20, 17],
        [20, 22, 19, 19]],

       [[20, 18, 19, 22],
        [19, 22, 18, 17],
        [19, 20, 17, 21]]])

In [51]:
my_array.ndim

3

### Задача 5

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:
    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

In [52]:
np.where(my_array < 20, 'small', (np.where(my_array>30, 'large', 'medium')))

array([[['medium', 'medium', 'small', 'small'],
        ['small', 'medium', 'medium', 'small'],
        ['medium', 'medium', 'small', 'small']],

       [['medium', 'small', 'small', 'medium'],
        ['small', 'medium', 'small', 'small'],
        ['small', 'medium', 'small', 'medium']]], dtype='<U6')

### Задача 6

* Напишите функцию, которая выполняет умножение двух матриц.
* Сравните производительность по времени своей функции со встроенным методом .dot

In [53]:
array1 = np.random.randint(1, 5, size=(4,2))
array2 = np.random.randint(1, 5, size=(2,4))
print(f'матрица 1:\n\n{array1}\n\nматрица 2:\n\n{array2}')

матрица 1:

[[1 1]
 [2 2]
 [4 2]
 [4 1]]

матрица 2:

[[1 1 4 1]
 [1 1 3 1]]


In [54]:
def mtrx_mlt(array1, array2):
    # завожу переменную под результирующую матрицу
    result = np.zeros((array1.shape[0], array1.shape[0]))
    # обхожу строки матрциы 1
    for i in range(array1.shape[0]):
        # обхожу столбцы матрицы 2
        for j in range(array2.shape[1]):
            # обхожу строки матрциы 1
            for el in range(array2.shape[0]):
                result[i][j] += array1[i][el] * array2[el][j]
    return result

mtrx_mlt(array1, array2)

array([[ 2.,  2.,  7.,  2.],
       [ 4.,  4., 14.,  4.],
       [ 6.,  6., 22.,  6.],
       [ 5.,  5., 19.,  5.]])

In [55]:
%timeit mtrx_mlt(array1, array2)

66.2 µs ± 5.12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [56]:
%timeit array1.dot(array2)

1.26 µs ± 82.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
